version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
- package-ecosystem: npm
  directory: "/shrtr"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
- package-ecosystem: npm
  directory: "/shrtrr"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - caiocampos
  assignees:
  - caiocampos
